### ISSUE TITLE
Multi-threading solving sometimes hangs.

### ISSUE THREAD

**Issue by yangdinglou** [potassco/clingo#528] opened 2024-11-28 12:55 UTC
Hi,

I am running multi-threading solving by `-tn` on my 8 core (M1 pro) Macbook, and find one program that can be only solved well by n<=6, but for -t7 or -t8, after all models are outputted, it hangs. Seems to be a Clingo bug because when I call the API `for (auto &m : solver.solve()) cout<<...`, the output is not complete.

The program contains something I cannot make it public here at this moment, but I'd like to send you if it helps to find the potential bug.

**Comment by rkaminsk** [comment] 2024-12-04 13:49
We can only help here if we get an example program. On another note, you should write your code as:
```
auto hnd = solver.solve();
for (auto &&m : hnd) {
    // ...
}
hnd.get();
```
If I remember correctly, the handle gets destroyed up to a certain revision of the C++ standard.

**Comment by yangdinglou** [comment] 2024-12-05 05:52
@rkaminsk I happened to identify the mini program that is going wrong.
```
pick_num(1,1).
pick_num(2,1).
pick_num(3,1).
1{pick(P,L,Pos):num(L),pos(Pos)}1:- pick_num(P,N).
num(1..20).
pos(0;1).

pick3(2*L1+Pos1,2*L2+Pos2,2*L3+Pos3):-pick(1,L1,Pos1),pick(2,L2,Pos2),pick(3,L3,Pos3).
```
Then hangs with `-t8 0` on my laptop.
It works alright either by reducing to `num(1..10)`, or deleting `pick3/3` rule.

Thanks for the hint on implementation.

**Comment by BenKaufmann** [comment] 2024-12-05 07:45
@yangdinglou Thanks. I can reproduce the issue here and will look into it.

**Comment by BenKaufmann** [comment] 2024-12-05 09:35
@yangdinglou Could you please verify whether your mini program really hangs indefinitely?  For me, it actually finishes after roughly **1 minute** where most of the time is spent on the transition from the last model to the end of search. 

While this behavior is unfortunate, it is technically not a bug but a consequence of **running one of the threads (solver 6) with full lookahead**.  All other threads are quick and together enumerate all `64000` models. However, the lookahead-based thread is still busy with its initial lookahead at this point. Only once this operation has finished, the overall algorithm can make progress. 

At least for me, if I run your program with `--lookahead=no -t8 0`,  termination is fast.

**Comment by yangdinglou** [comment] 2024-12-05 10:14
@BenKaufmann You are right (can confirm that it's ~70s). The task where I found this issue is larger so it looks like hanging forever. And I tried on that with `-lookahead=no`, resulting in normal termination.

May I know why the look-ahead threads work alright when deleting `pick3/3`?

**Comment by rkaminsk** [comment] 2024-12-05 10:34
> May I know why the look-ahead threads work alright when deleting `pick3/3`?

The rule with `pick3/3` in the head involves a huge cross-product. There are 20*2*20*2*20*2 instances of it if I am not mistaken. The lookahead on all those instances takes time.

@BenKaufmann: Would it be hard to stop the lookahead if there is a stop conflict?

**Comment by yangdinglou** [comment] 2024-12-05 11:08
That fits with my observation. Since disabling the lookahead works well, please close the issue whenever you think is okay.
Thanks

**Comment by BenKaufmann** [comment] 2024-12-05 11:14
> > May I know why the look-ahead threads work alright when deleting `pick3/3`?
> 
> The rule with `pick3/3` in the head involves a huge cross-product. There are `20*2*20*2*20*2` instances of it if I am not mistaken. The lookahead on all those instances takes time.

Yep. With `pick3/3`, lookahead checks up to `64236` nodes on each decision level compared to only `122`  without it - and lookahead is costly.

> @BenKaufmann: Would it be hard to stop the lookahead if there is a stop conflict?

No. And this is already happening in certain situations. E.g. if you run the above program with `--enum=record` (no sync required), request only a small number of models, or (asynchronously) interrupt the search, you'll see that termination is fast. 

However, the default (splitting-based) enumeration of **all** models has to wait for the lookahead thread at certain points. E.g. assume T0 solves path `a` without lookahead, while T1 solves `-a` with lookahead. Once T0 has enumerated all models under `a`, it has to ask T1 for more work but T1 can only produce more work once it has finished lookahead of the first level. To make this more responsive, we'd have to integrate lookahead more tightly into the parallel algorithm.

**Comment by BenKaufmann** [comment] 2024-12-09 13:47
Improved responsiveness of lookahead during parallel solving. Currently, the change is only in clasp's dev branch but it will be part of clingo  v5.7.2.

**Closed by BenKaufmann** 2024-12-09 13:47 UTC
Labels: enhancement
