### ISSUE TITLE
Multi-Shot Performance Degradation

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#176] opened 2019-11-07 12:18 UTC
I currently do solve an optimization problem that contains a certain bound/horizon X.
I want to find a minimal solution within this bound. So if i set the bound X=500 and solve the problem i do get a minimal solution with a value of 267. So, obviously I could have set the bound X=300 to save on grounding/solving time and reduce the search space and still find a minimal solution with value 267. If I would have reduced the bound too much, like X=200 I would simply get UNSAT.

Now I have rewritten my encoding to incrementally increase this bound (X=0, X=100, X=200, ...) to save on grounding/solving time. Doing this, using the command line, needs to reground everything before and nothing can be reused. Doing this using the multi-shot interface, I can reuse old rules, retract a tiny percent of the old rules and add new rules.

The results that I got are the following:
Manual Incremental Solving using command line and the original Encoding:
X=0:

> Progression : [60;inf]                                                                                                
> Progression : [120;inf]                                                                                               
> Progression : [180;inf]                                                                                               
> Progression : [186;inf]                                                                                               
> Progression : [192;inf]                                                                                               
> UNSATISFIABLE                                                                                                         
>                                                                                                                       
> Models       : 0                                                                                                      
> Calls        : 1                                                                                                      
> Time         : 3.911s (Solving: 0.07s 1st Model: 0.00s Unsat: 0.07s)                                                  
> CPU Time     : 3.972s                                                                                                 
> Threads      : 2        (Winner: 0)                                                                                   
>                                                                                                                       
> Choices      : 7614     (Domain: 6615)                                                                                
> Conflicts    : 35       (Analyzed: 17)                                                                                
> Restarts     : 0                                                                                                      
> Problems     : 7        (Average Length: 0.29 Splits: 0)                                                              
> Lemmas       : 194      (Deleted: 0)                                                                                  
>   Binary     : 64       (Ratio:  32.99%)                                                                              
>   Ternary    : 45       (Ratio:  23.20%)                                                                              
>   Conflict   : 17       (Average Length:    2.2 Ratio:   8.76%)                                                       
>   Loop       : 0        (Average Length:    0.0 Ratio:   0.00%)                                                       
>   Other      : 177      (Average Length:    2.7 Ratio:  91.24%)                                                       
>   Distributed: 80       (Ratio: 470.59% Average LBD: 100.45)                                                          
>   Integrated : 80       (Ratio: 100.00% Unit: 25 Average Jumps: 45.48)                                                
> Backjumps    : 17       (Average: 15.06 Max:  48 Sum:    256)                                                         
>   Executed   : 15       (Average: 14.82 Max:  48 Sum:    252 Ratio:  98.44%)                                          
>   Bounded    : 2        (Average:  2.00 Max:   2 Sum:      4 Ratio:   1.56%)                                          
>                                                                                                                       
> Rules        : 893170                                                                                                 
>   Choice     : 4763                                                                                                   
>   Minimize   : 2                                                                                                      
>   Heuristic  : 4311                                                                                                   
> Atoms        : 854848                                                                                                 
> Bodies       : 50499                                                                                                  
>   Count      : 46                                                                                                     
> Equivalences : 114738   (Atom=Atom: 33882 Body=Body: 18683 Other: 62173)                                              
> Tight        : Yes                                                                                                    
> Variables    : 9908     (Eliminated:    0 Frozen: 9908)                                                               
> Constraints  : 35574    (Binary:  64.9% Ternary:  31.9% Other:   3.2%)

X=225000

> Progression : [1;inf]
> Progression : [2;inf]
> Progression : [3;inf]
> Progression : [4;inf]
> Progression : [5;inf]
> Progression : [6;inf]                                                                                                 
> Progression : [7;inf]                                                                                                 
> Progression : [8;inf]                                                                                                 
> UNSATISFIABLE
> 
> Models       : 0
> Bounds       : [8;*] [0;*]
> Calls        : 1                                                                                                      
> Time         : 4.387s (Solving: 0.22s 1st Model: 0.00s Unsat: 0.22s)                                                  
> CPU Time     : 4.604s   
> Threads      : 2        (Winner: 0)                                                                                   
> 
> Choices      : 23742    (Domain: 18106)                                                                               
> Conflicts    : 72       (Analyzed: 60)
> Restarts     : 0        
> Problems     : 10       (Average Length: 0.20 Splits: 0) 
> Lemmas       : 557      (Deleted: 0)
>   Binary     : 158      (Ratio:  28.37%)    
>   Ternary    : 123      (Ratio:  22.08%)
>   Conflict   : 59       (Average Length:    5.3 Ratio:  10.59%) 
>   Loop       : 0        (Average Length:    0.0 Ratio:   0.00%)                                                       
>   Other      : 498      (Average Length:    4.1 Ratio:  89.41%) 
>   Distributed: 170      (Ratio: 288.14% Average LBD: 93.28)  
>   Integrated : 170      (Ratio: 100.00% Unit: 27 Average Jumps: 67.07)                                                
> Backjumps    : 60       (Average: 44.28 Max: 745 Sum:   2657)                                                         
>   Executed   : 49       (Average: 11.40 Max: 745 Sum:    684 Ratio:  25.74%)                                          
>   Bounded    : 11       (Average: 179.36 Max: 741 Sum:   1973 Ratio:  74.26%)                                         
>   
> Rules        : 957799                                                                                                 
>   Choice     : 8312                                                                                                   
>   Minimize   : 2                                                                                                      
>   Heuristic  : 7048     
> Atoms        : 887913                                                                                                 
> Bodies       : 83670    
>   Count      : 46       
> Equivalences : 181546   (Atom=Atom: 52863 Body=Body: 27977 Other: 100706)                                             
> Tight        : Yes                                                                                                    
> Variables    : 15541    (Eliminated:    0 Frozen: 15541)                                                              
> Constraints  : 57853    (Binary:  62.2% Ternary:  34.9% Other:   2.8%)

X=450000

> OPTIMUM FOUND
> 
> Models       : 29
>   Optimum    : yes
> Optimization : 540013 360
> Calls        : 1
> Time         : 5.749s (Solving: 1.32s 1st Model: 0.85s Unsat: 0.01s)
> CPU Time     : 7.044s
> Threads      : 2        (Winner: 1)
> 
> Choices      : 156314   (Domain: 111548)
> Conflicts    : 2416     (Analyzed: 2351)
> Restarts     : 5        (Average: 470.20 Last: 121)
> Model-Level  : 1234.8
> Problems     : 66       (Average Length: 0.03 Splits: 0)
> Lemmas       : 3833     (Deleted: 0)
>   Binary     : 302      (Ratio:   7.88%)
>   Ternary    : 418      (Ratio:  10.91%)
>   Conflict   : 2351     (Average Length:   18.8 Ratio:  61.34%)
>   Loop       : 0        (Average Length:    0.0 Ratio:   0.00%)
>   Other      : 1482     (Average Length:    5.5 Ratio:  38.66%)
>   Distributed: 471      (Ratio:  20.03% Average LBD: 92.73)
>   Integrated : 471      (Ratio: 100.00% Unit: 48 Average Jumps: 71.54)
> Backjumps    : 2351     (Average:  5.09 Max: 1233 Sum:  11962)
>   Executed   : 2309     (Average:  3.24 Max: 1233 Sum:   7618 Ratio:  63.69%)
>   Bounded    : 42       (Average: 103.43 Max: 1169 Sum:   4344 Ratio:  36.31%)
> 
> Rules        : 1022697
>   Choice     : 11112
>   Minimize   : 2
>   Heuristic  : 9442
> Atoms        : 916954
> Bodies       : 116181
>   Count      : 46
> Equivalences : 244095   (Atom=Atom: 71055 Body=Body: 38420 Other: 134620)
> Tight        : Yes
> Variables    : 20362    (Eliminated:    0 Frozen: 20362)
> Constraints  : 79753    (Binary:  59.0% Ternary:  38.2% Other:   2.8%)

With the incremental approach I do get the following results:

> Progression : [60;inf]
> Progression : [120;inf]
> Progression : [180;inf]
> Progression : [240;inf]
> Progression : [300;inf]
> UNSATISFIABLE
> 
> Models       : 0
> Time         : 4.138s (Solving: 0.06s 1st Model: 0.00s Unsat: 0.06s)
> CPU Time     : 4.192s
> Threads      : 2        (Winner: 1)
> 
> Choices      : 7908     (Domain: 7064)
> Conflicts    : 53       (Analyzed: 13)
> Restarts     : 0
> Problems     : 7        (Average Length: 0.57 Splits: 0)
> Lemmas       : 148      (Deleted: 0)
>   Binary     : 44       (Ratio:  29.73%)
>   Ternary    : 53       (Ratio:  35.81%)
>   Conflict   : 13       (Average Length:    3.0 Ratio:   8.78%)
>   Loop       : 0        (Average Length:    0.0 Ratio:   0.00%)
>   Other      : 135      (Average Length:    3.5 Ratio:  91.22%)
>   Distributed: 55       (Ratio: 423.08% Average LBD: 99.87)
>   Integrated : 54       (Ratio:  98.18% Unit: 23 Average Jumps: 45.13)
> Backjumps    : 13       (Average: 30.31 Max:  69 Sum:    394)
>   Executed   : 11       (Average: 25.69 Max:  69 Sum:    334 Ratio:  84.77%)
>   Bounded    : 2        (Average: 30.00 Max:  36 Sum:     60 Ratio:  15.23%)
> 
> Rules        : 1050257
>   Choice     : 4763
>   Minimize   : 2
>   Heuristic  : 4311
> Atoms        : 1011936
> Bodies       : 50500
>   Count      : 46
> Equivalences : 99987    (Atom=Atom: 26783 Body=Body: 18683 Other: 54521)
> Tight        : Yes
> Variables    : 9909     (Eliminated:    0 Frozen: 8344)
> Constraints  : 35590    (Binary:  64.9% Ternary:  31.9% Other:   3.2%)
> 
> Solving...
> Progression : [180007;inf]
> Progression : [180008;inf]
> Progression : [225008;inf]
> UNSATISFIABLE
> 
> Models       : 0
> Bounds       : [225008;*] [0;*]
> Time         : 11.407s (Solving: 10.32s 1st Model: 0.00s Unsat: 10.32s)
> CPU Time     : 21.724s
> Threads      : 2        (Winner: 0)
> 
> Choices      : 57821    (Domain: 44147)
> Conflicts    : 105      (Analyzed: 92)
> Restarts     : 0
> Problems     : 13       (Average Length: 0.31 Splits: 0)
> Lemmas       : 653      (Deleted: 0)
>   Binary     : 153      (Ratio:  23.43%)
>   Ternary    : 187      (Ratio:  28.64%)
>   Conflict   : 90       (Average Length:    5.5 Ratio:  13.78%)
>   Loop       : 0        (Average Length:    0.0 Ratio:   0.00%)
>   Other      : 563      (Average Length:    4.5 Ratio:  86.22%)
>   Distributed: 215      (Ratio: 238.89% Average LBD: 87.10)
>   Integrated : 213      (Ratio:  99.07% Unit: 43 Average Jumps: 178.16)
> Backjumps    : 92       (Average: 64.78 Max: 737 Sum:   5960)
>   Executed   : 76       (Average: 20.86 Max: 737 Sum:   1919 Ratio:  32.20%)
>   Bounded    : 16       (Average: 252.56 Max: 732 Sum:   4041 Ratio:  67.80%)
> 
> Rules        : 1119270
>   Choice     : 8718
>   Minimize   : 3
>   Heuristic  : 7048
> Atoms        : 1049370
> Bodies       : 84124
>   Count      : 46
> Equivalences : 166520   (Atom=Atom: 44279 Body=Body: 27530 Other: 94711)
> Tight        : Yes
> Variables    : 16079    (Eliminated:    0 Frozen: 13849)
> Constraints  : 57800    (Binary:  62.5% Ternary:  34.7% Other:   2.8%)
> 
> OPTIMUM FOUND
> 
> Models       : 163
>   Optimum    : yes
> Optimization : 630013 360
> Time         : 207.521s (Solving: 206.78s 1st Model: 28.36s Unsat: 0.01s)
> CPU Time     : 414.264s
> Threads      : 2        (Winner: 0)
> 
> Choices      : 562026   (Domain: 378073)
> Conflicts    : 25447    (Analyzed: 25020)
> Restarts     : 62       (Average: 403.55 Last: 0)
> Model-Level  : 1924.5
> Problems     : 428      (Average Length: 0.01 Splits: 0)
> Lemmas       : 27649    (Deleted: 8371)
>   Binary     : 523      (Ratio:   1.89%)
>   Ternary    : 934      (Ratio:   3.38%)
>   Conflict   : 25020    (Average Length:   34.0 Ratio:  90.49%)
>   Loop       : 0        (Average Length:    0.0 Ratio:   0.00%)
>   Other      : 2629     (Average Length:    6.6 Ratio:   9.51%)
>   Distributed: 731      (Ratio:   2.92% Average LBD: 98.01)
>   Integrated : 731      (Ratio: 100.00% Unit: 86 Average Jumps: 298.60)
> Backjumps    : 25020    (Average:  2.12 Max: 744 Sum:  52947)
>   Executed   : 24770    (Average:  1.67 Max: 744 Sum:  41679 Ratio:  78.72%)
>   Bounded    : 250      (Average: 45.07 Max: 741 Sum:  11268 Ratio:  21.28%)
> 
> Rules        : 1192380
>   Choice     : 11924
>   Minimize   : 4
>   Heuristic  : 9442
> Atoms        : 1086561
> Bodies       : 118074
>   Count      : 46
> Equivalences : 235121   (Atom=Atom: 63824 Body=Body: 37247 Other: 134050)
> Tight        : Yes
> Variables    : 21397    (Eliminated:    0 Frozen: 18494)
> Constraints  : 79607    (Binary:  59.3% Ternary:  37.9% Other:   2.8%)

I additionally use multi-threading (2threads) and theory solving (DLPropagator).
My questions is now, why is the solving process so much slower, given a similar search behaviour, number of variables and constraints.
The first step X=0 is nearly identical, same grounding and solving time, similar conflicts and choices.
The second step X=225000 the manual version took 4s grounding time (it had to reground the first step completely) and 0.22s solving time to proof unsat with 23k choices and 72 conflicts.
Doing exactly the same using the multi-shot API the grounding too only 1s (as it simply had to add some rules) but solving took 10s to prove unsat.
Normally I would say that this can happen if the search gets confused, but the number of choices is 57k with 107 conflicts. So its double the choices, but the time is 50 times higher.
Where does this time go and what makes search so slow. The statistics of the DLPropagator show that it uses nearly no time (thats why I did not included it here).
Any idea why unit propagation speed degrades by 5000% ? It seems somehow related to the multishot approach.

**Comment by MaxOstrowski** [comment] 2019-11-07 12:38
Same behaviour without multi-threading.

**Comment by rkaminsk** [comment] 2019-11-07 13:00
Sorry, but I cannot tell you. It could be the restricted preprocessing or just heuristic effects. You could try to experiment with the forgetting options.

**Comment by MaxOstrowski** [comment] 2019-11-07 13:04
- Given that I use the theory interface and clingo-dl, sat-prepro is disabled in both cases, and you can see that no variables were eliminated anywhere.
- Heuristic effects In my opinion are possible but do not explain the results. 2 times the amount of choices can be a heuristic effect, but not 50 times the raw propagation performance. Same with forgetting options, this should have an influence on choices/conflicts but not on raw speed. I will try nevertheless.

**Comment by rkaminsk** [comment] 2019-11-07 13:18
Note that there is more than just sat preprocessing. I cannot tell from the statistics where the problem is. You could profile the code to figure out where most time is spent.

**Comment by MaxOstrowski** [comment] 2019-11-07 13:23
Thanks. I simply doubt that the result/lack of preprocessing the the cause, as the number of constraint(and their sizes)/variables  is very similar. Will try to figure out how to profile this setup.

**Comment by MaxOstrowski** [comment] 2019-11-07 13:29
`--forget-on-step=15`
has some impact but the problem stays the same.

**Comment by MaxOstrowski** [comment] 2019-11-08 13:34
Unsure if this is going off topic.
This is part of the callgrind analysis, unsure how to interpret it:
```
--------------------------------------------------------------------------------
273,665,234,990  PROGRAM TOTALS

--------------------------------------------------------------------------------
            Ir  file:function
--------------------------------------------------------------------------------
38,031,950,558  libclingo-dl/clingo-dl/propagator.hh:DifferenceLogicPropagator<int>::check(Clingo::PropagateControl&) [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo-dl.so]
37,699,274,344  clingo/clasp/src/clingo.cpp:Clasp::ClingoAssignment::value(int) const [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
36,469,261,288  clingo/libclingo/clingo.hh:DifferenceLogicPropagator<int>::check(Clingo::PropagateControl&)
25,527,669,678  clingo/clasp/libpotassco/src/clingo.cpp:Potassco::AbstractAssignment::isTrue(int) const [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
25,527,669,678  clingo/libclingo/src/control.cc:clingo_assignment_is_true [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
21,880,859,724  clingo/clasp/clasp/literal.h:Clasp::ClingoAssignment::value(int) const
11,745,086,126  /usr/include/c++/6/bits/stl_vector.h:DifferenceLogicPropagator<int>::check(Clingo::PropagateControl&)
10,942,400,772  clingo/libclingo/clingo.hh:Clingo::Detail::handle_error(bool) [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo-dl.so]
10,940,429,862  clingo/clasp/clasp/solver_types.h:Clasp::ClingoAssignment::value(int) const
 7,294,091,326  clingo/libclingo/src/control.cc:clingo_propagate_control_assignment [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
 7,294,091,326  clingo/clasp/src/clingo.cpp:Clasp::ClingoPropagator::Control::assignment() const [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
 7,293,619,908  clingo/clasp/clasp/solver.h:Clasp::ClingoAssignment::value(int) const
 1,254,110,579  /build/glibc-77giwP/glibc-2.24/malloc/malloc.c:_int_malloc [/lib/x86_64-linux-gnu/libc-2.24.so]
 1,182,487,956  clingo/libgringo/gringo/utility.hh:Gringo::String::String(char const*)
 1,061,556,013  /build/glibc-77giwP/glibc-2.24/string/../sysdeps/x86_64/multiarch/strcmp-sse2-unaligned.S:__strcmp_sse2_unaligned [/lib/x86_64-linux-gnu/libc-2.24.so]
 1,029,900,309  clingo/libgringo/src/term.cc:Gringo::FunctionTerm::match(Gringo::Symbol const&) const [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
 1,011,683,124  clingo/libgringo/gringo/utility.hh:Gringo::Symbol::createFun(Gringo::String, Potassco::Span<Gringo::Symbol>, bool)
   888,434,639  clingo/libgringo/src/symbol.cc:Gringo::Symbol::args() const [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
   864,098,538  /build/glibc-77giwP/glibc-2.24/malloc/malloc.c:_int_free [/lib/x86_64-linux-gnu/libc-2.24.so]
   793,609,011  clingo/libgringo/src/term.cc:Gringo::FunctionTerm::eval(bool&, Gringo::Logger&) const [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
   709,610,395  libclingo-dl/clingo-dl/propagator.hh:bool DifferenceLogicGraph<int>::add_edge<DifferenceLogicPropagator<int>::do_propagate(Clingo::PropagateControl&, Clingo::Span<int, Clingo::ToIterator<int> >)::{lambda(std::vector<int, std::allocator<int> > const&) [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo-dl.so]
   672,178,680  /build/glibc-77giwP/glibc-2.24/nptl/../nptl/pthread_mutex_lock.c:pthread_mutex_lock [/lib/x86_64-linux-gnu/libpthread-2.24.so]
   635,318,853  clingo/libgringo/src/symbol.cc:Gringo::Symbol::createFun(Gringo::String, Potassco::Span<Gringo::Symbol>, bool) [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
   635,099,287  clingo/libgringo/gringo/hash_set.hh:Gringo::Symbol::createFun(Gringo::String, Potassco::Span<Gringo::Symbol>, bool)
   593,171,375  clingo/libgringo/src/ground/instantiation.cc:Gringo::Ground::Instantiator::instantiate(Gringo::Output::OutputBase&, Gringo::Logger&) [/home/ostrowsk/work/krbiz/gitpotassco/clingoDL/build/bin/libclingo.so.3.0]
   573,535,599  clingo/libgringo/gringo/hash_set.hh:Gringo::String::String(char const*)
```

Looks like clingo-dl:check takes most of the time, but not actually the propagation (but there is not much going on besides the do_propagate method.

**Comment by rkaminsk** [comment] 2019-11-08 14:01
Marking as invalid and closing because it turned out to be a clingo-dl problem.

**Closed by rkaminsk** 2019-11-08 14:01 UTC
Labels: invalid, question
