### ISSUE TITLE
--time-limit=<n> not working as expected

### ISSUE THREAD

**Issue by Pangurbon** [potassco/clingo#122] opened 2018-09-04 07:46 UTC
I'm having trouble figuring out if this is a user error or not. Neither --time-limit=<n> nor -W no-operation-undefined seem to change the behavior of clingo or clasp. If I set the time limit to 10, it should terminate at that point if it hasn't finished correct? Trying to remove the operation-undefined warning from output doesn't seem to work either.

Documentation on the CLI parameters is a bit sparse so I may just be using them incorrect!

**Comment by Pangurbon** [comment] 2018-09-11 06:15
To be honest I'm having trouble reproducing it myself. I will attach an example in sometime tomorrow. But I think I've found a common theme. Whenever I'm running things in parallel (using jobs in Powershell) I get some strange behavior with the time-limits. Would multiple clingo instances running at once cause an issue here? Everything else seems to work fine.

**Comment by rkaminsk** [comment] 2018-09-16 19:00
Multiple clingo versions should not interfere with each other. Are you running the clingo versions with multiple threads (`--parallel-mode,-t`)? There have been problems with shutting down in the past, which we tried to fix in the latest versions. You can try option `--fast-exit` if there are hangs while shutting down.

In any case, if the problem is with clingo and not with the powershell scripts, it would be helpful, if you could attach something reproducible. Then we can fix it in the next release.

We have some information about options in the guide but this is not very exhaustive (and is hopefully not outdated). I doubt that anyone is writing anything more soon.

**Comment by rkaminsk** [comment] 2018-11-04 18:10
I am going to close this, since there is no further info. Feel free to reopen.

**Closed by rkaminsk** 2018-11-04 18:10 UTC
Labels: unconfirmed
