### ISSUE TITLE
OSX build from source

### ISSUE THREAD

**Issue by hfurkanbozkurt** [potassco/clingo#119] opened 2018-07-16 15:55 UTC
I am trying to build clingo from source on Early 2015 Macbook Pro with MacOS High Sierra 10.13.5.
After downloading the code and updating submodules, I can create the build configuration with 
`cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release`. When I run `cmake --build build`, I encounter with this error:

[ 12%] Built target libpotassco
[ 14%] Built target lpconvert
[ 42%] Built target libclasp
[ 44%] Built target clasp
[ 46%] Built target libreify
[ 47%] Building CXX object libgringo/CMakeFiles/libgringo.dir/src/ground/instantiation.cc.o
In file included from /home/bozkurth/work/clingo/libgringo/gringo/output/statements.hh:29:0,
                 from /home/bozkurth/work/clingo/libgringo/gringo/output/output.hh:29,
                 from /home/bozkurth/work/clingo/libgringo/src/ground/instantiation.cc:26:
/home/bozkurth/work/clingo/libgringo/gringo/output/literals.hh:504:22: error: function 'Gringo::Output::DisjointElement& Gringo::Output::DisjointElement::operator=(Gringo::Output::DisjointElement&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'Gringo::Output::DisjointElement& Gringo::Output::DisjointElement::operator=(Gringo::Output::DisjointElement&&)'
     DisjointElement &operator=(DisjointElement &&) noexcept = default;
                      ^
/home/bozkurth/work/clingo/libgringo/gringo/output/literals.hh:524:19: error: function 'Gringo::Output::DisjointAtom& Gringo::Output::DisjointAtom::operator=(Gringo::Output::DisjointAtom&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'Gringo::Output::DisjointAtom& Gringo::Output::DisjointAtom::operator=(Gringo::Output::DisjointAtom&&)'
     DisjointAtom &operator=(DisjointAtom &&) noexcept = default;
                   ^
libgringo/CMakeFiles/libgringo.dir/build.make:149: recipe for target 'libgringo/CMakeFiles/libgringo.dir/src/ground/instantiation.cc.o' failed
make[2]: *** [libgringo/CMakeFiles/libgringo.dir/src/ground/instantiation.cc.o] Error 1
CMakeFiles/Makefile2:473: recipe for target 'libgringo/CMakeFiles/libgringo.dir/all' failed
make[1]: *** [libgringo/CMakeFiles/libgringo.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by rkaminsk** [comment] 2018-07-16 16:18
Can't tell from the log why this is happening. My guess is that the compiler you are using is too old. When I am running cmake, I get the following:

```
cmake ..
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
```

Make sure your xcode installation is new enough.

**Comment by hfurkanbozkurt** [comment] 2018-07-16 16:49
I have stated the problem wrong.

The log in my first post is from my remote machine which uses Ubuntu with 

`cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5`

On my machine, I get the same output as yours:

`cmake ..
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039`

And the error log is:

`[ 10%] Building CXX object clasp/libpotassco/src/CMakeFiles/libpotassco.dir/string_convert.cpp.o
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp:58:9: error: ‘locale_t’ does not name a type
 typedef locale_t my_locale_t;
         ^
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp:59:8: error: ‘my_locale_t’ does not name a type
 inline my_locale_t default_locale() { return newlocale(LC_ALL_MASK, "C", 0); }
        ^
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp:63:2: error: ‘my_locale_t’ does not name a type
  my_locale_t loc_;
  ^
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp: In destructor ‘LocaleHolder::~LocaleHolder()’:
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp:62:31: error: ‘loc_’ was not declared in this scope
  ~LocaleHolder() { freelocale(loc_);  }
                               ^
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp:62:35: error: ‘freelocale’ was not declared in this scope
  ~LocaleHolder() { freelocale(loc_);  }
                                   ^
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp: At global scope:
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp:64:39: error: ‘default_locale’ was not declared in this scope
 } default_locale_g = { default_locale() };
                                       ^
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp: In function ‘int Potassco::xconvert(const char*, double&, const char**, int)’:
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp:230:43: error: ‘struct LocaleHolder’ has no member named ‘loc_’
  out = strtod_l(x, &err, default_locale_g.loc_);
                                           ^
/Users/bozkurth/Work/hiwi/clingo_swig/clingo/clasp/libpotassco/src/string_convert.cpp:230:47: error: ‘strtod_l’ was not declared in this scope
  out = strtod_l(x, &err, default_locale_g.loc_);
                                               ^
make[2]: *** [clasp/libpotassco/src/CMakeFiles/libpotassco.dir/string_convert.cpp.o] Error 1
make[1]: *** [clasp/libpotassco/src/CMakeFiles/libpotassco.dir/all] Error 2
make: *** [all] Error 2`

**Comment by rkaminsk** [comment] 2018-07-16 18:19
You need at least gcc 4.9. I gave up supporting version 4.8 long ago.

The errors on MacOS I cannot reproduce. I have the same compiler here. Looks like something with your includes goes wrong.

**Comment by rkaminsk** [comment] 2018-07-18 10:50
One more thing that comes to my mind is that you might have to run `xcode-select --install` to install the latest xcode command line tools.

**Comment by rkaminsk** [comment] 2018-07-25 12:50
I am closing this because I cannot reproduce the issue. Feel free to reopen if you have more information.

**Closed** 2018-07-25 12:50 UTC
Labels: invalid
