### ISSUE TITLE
How to use the field type in clingo_ast_external

### ISSUE THREAD

**Issue by sthiele** [potassco/clingo#160] opened 2019-07-20 20:52 UTC
The ast.c example does not use the field `type`. Can you please explain how it would be set. 

    // external
    typedef struct clingo_ast_external {
        clingo_ast_term_t atom;
        clingo_ast_body_literal_t const *body;
        size_t size;
        clingo_ast_term_t type;
    } clingo_ast_external_t;

**Comment by rkaminsk** [comment] 2019-07-29 10:16
I extended the syntax to allow for adding flags to externals. Now, you can write:

    #external a. [false]

This is also reflected in the AST. The type member is for the term in the brackets.

I forgot to update the example. The issue is fixed in the associated commit.

**Closed by rkaminsk** 2019-07-29 10:16 UTC
Labels: bug
