### ISSUE TITLE
All atoms are not generated

### ISSUE THREAD

**Issue by Aluriak** [potassco/clingo#47] opened 2017-06-30 15:28 UTC
I recently came across the following behavior (clingo 5 and clingo 4.5.4).

    % Input data: a context containing two concepts.
    rel((a;b;c;d),(e;f)).  % first concept
    rel((a;b),(g;h)).  % second concept (overlapping the first on {a,b})

    % Generation of formal concepts (1 concept = 1 answer set).
    obj(X):- rel(X,_) ; rel(X,Y): att(Y).
    att(Y):- rel(_,Y) ; rel(X,Y): obj(X).

    % Outsiders are objects in the concept that are linked to non-attribute values.
    outsider(X):- obj(X) ; rel(X,Z) ; not att(Z).
    % This line should, for the first answer set, yield outsider(a) and outsider(b).
    % Observation: it doesn't.

    #show.
    #show obj/1.
    #show att/1.
    #show outsider/1.

Using `clingo -n 0 file.lp`, i got the following answer sets:

    Answer: 1
    att(f) att(e) obj(b) obj(a) obj(d) obj(c)
    Answer: 2
    att(f) att(e) obj(b) obj(a) att(h) att(g)
    SATISFIABLE

The second one is missing the atoms `outsider(a)` and `outsider(b)` (since both are in obj/1, and linked to g which is not in att/1).

I found two way to retrieve correctly these missing atoms.

#### 1. By changing a little the definition of outsider/1, using an intermediary object:

    not_att(Z):- not att(Z) ; rel(_,Z).
    outsider(X):- obj(X) ; rel(X,Z) ; not_att(Z).
    % This time, outsider(a) and outsider(b) are generated.

#### 2 .By replacing the concept generation by the expected obj/1 and att/1:

    % Obviously, only one answer set remains, but at least we got the outsider/1 atoms correctly.
    att(f). att(e). obj(b). obj(a). obj(d). obj(c).

**Comment by Aluriak** [comment] 2017-06-30 15:33
I tried these codes with the clingo compiled using code in branch *fix_issue_46*.
It seems to fix the problem.

Follow the lines missing in clingo5 grounding, compared to clingo 5 with bugfix #46.

    < outsider(d):-obj(d),not att(f).
    < outsider(c):-obj(c),not att(f).
    < outsider(b):-obj(b),not att(f).
    < outsider(b):-obj(b),not att(g).
    < outsider(b):-obj(b),not att(h).
    < outsider(a):-obj(a),not att(f).
    < outsider(a):-obj(a),not att(g).
    < outsider(a):-obj(a),not att(h).

**Comment by rkaminsk** [comment] 2017-06-30 16:46
Yes, this is the same as issue #46. The problem is that the component

    obj(X):- rel(X,_) ; rel(X,Y): att(Y).
    att(Y):- rel(_,Y) ; rel(X,Y): obj(X).

is classified as a positive program. Because of this, grounding

    outsider(X):- obj(X) ; rel(X,Z) ; not_att(Z).

results in only one ground rule for each possible `X`. I am going to close this as a duplicate.

**Closed by rkaminsk** 2017-06-30 16:46 UTC
