### ISSUE TITLE
Add a build-in predicate that checks whether a variable is a number

### ISSUE THREAD

**Issue by teiesti** [potassco/clingo#343] opened 2021-10-29 16:32 UTC
I'd like to propose the addition of a build-in predicate `number/1` (name must be debated!) that checks if a variable is a number. E.g. the following example should derive `bar(1)` but not `bar((1,1))`.

```
foo(1).
foo((1,1)).
bar(X) :- foo(X), number(X).
```

It is actually possible to simulate the requested behavior this way (credits go to @MaxOstrowski):
```
foo(1).
foo((1,1)).
bar(X) :- foo(X), Y=X+1.
```

But, I'd say, this is not quite intuitive even for an experienced modeler.

One could also add build-in predicate for other types, like tuples, string, ...

**Comment by daveraja** [comment] 2021-10-29 23:17
I'm not sure that built-in predicates are the right way to go; or at least not without some clear syntactic marker to indicate that this is not a normal predicate but a special type checking predicate. 

I agree that `Y=X+1` is not an intuitive way of testing that Y is a number so if I was doing it I would probably write a python function to do these checks. Something like:

           bar(X) :- foo(X), @check(X, number) == 1.
           bar(X) :- foo2(X), @check(X, tuple) == 1.

If you found this too verbose and were committed to the built-in predicates idea you could potentially hook into the AST to do some re-writing of the special predicates into these python checks.

However, in general I'm not sure how useful type checking is for ASP programming. Most of my mistakes that would lead to a type error would be the result of variable name typos. And type checking would only pick up some of these mistakes.

But I do think that linters and other IDE tools (maybe a Language Server Protocol for ASP?) would be incredibly useful, so a discussion about these ideas is worth having.

**Comment by daveraja** [comment] 2021-10-29 23:32
@teiesti  I just realised that I made an assumption that you would want the built-in predicates as a type checking mechanism to find mistakes, rather than filtering terms of different types as part of the way you model a given problem.

I guess I rarely model in that way and the rare times I would need it I would probably do some trick like Max suggested... so I haven't added to the conversation :(

**Comment by rkaminsk** [comment] 2021-10-30 08:41
In other programming languages `dynamic_cast`s, `isinstance` calls, or related are typically a sign of code smell. There are rare cases where such functions have their uses. Maybe hidden behind a nice interface in a library implementation. Right now I would rather not implement something like this because I see no need in ASP. Except if you can give me one of those rare cases where this would be incredibly useful.

And even then, maybe the following is enough:
```python
#script(python)
from clingo.symbol import Function
def symbol_type(x):
   return Function(str(x.type).replace('SymbolType', ''), [])
#end.
```

**Comment by teiesti** [comment] 2021-10-30 15:58
Mhmm, I don't think I have such a use case.

What I am trying to do is somehow similar to *operator overloading* in other programming languages. I am doing that to provide an ergonomic input language that is easy to understand.

Let me share my example: I have a predicate called `has_a` that is defined as follows.

> `has_a(Wt, Pn, X)`
> Type `Wt` has one or more parts that are collectively named `Pn`.
> `X` specifies the type and cardinality of `Pn` and can either be
>   - `Pt`, where `Pt` is a type and the cardinality of `Pn` is `1`,
>   - `(Pt, C)`, where `Pt` is a type and `C` is a natural number excluding `0` denoting the cardinality of `Pn`, or
>   - `(Pt, (L, U))`, where `Pt` is a type, `L` is a natural number including `0` denoting the lower bound, and `U` is either a natural number excluding `O` or `inf` denoting the upper bound of the cardinality of `Pn`.

The idea is that a user can specify whole-part relations with increasing complexity, e.g.
- `has_a(my_car, engine, engine)`: `my_car` has one engine named `engine` of type `engine`.   
- `has_a(my_car, wheels, (wheel, 4))`: `my_car` has exactly four wheels.
- `has_a(my_car, doors, (door, (2,5)))`: `my_car` has between 2 and 5 doors.

For computation purposes, all the simple forms are translated into the most difficult one. I use the following rules for that:
```
has_a(Wt, Pn, (Pt, (C, C))) :- has_a(Wt, Pn, (Pt, C)), C = X + 1.
has_a(Wt, Pn, (Pt, (1, 1))) :- has_a(Wt, Pn, Pt), type(Pt).
```

If you think about these rules, you notice that you immediately get an infinite recursion if you remove `C = X + 1` or `type(Pt)`, since `C` and `Pt` could also be instantiated with a tuple.

This issue asks for a more intuitive replacement for `C = X + 1`.

By the way: I am definitely not saying that there is no simple solution to avoid the infinite recursion. One could simply remove all tuples and use `has_a`-predicates of arity 4 and 5, instead of only having arity 3.

My problem with that is
1. that the tuples carry a meaning for the reader, since their group knowledge that belongs together, and
2. I later plan to use `has_a(Wt, Pn, X)` for other purposes without thinking what X exactly is (at least unless necessary).

**Comment by daveraja** [comment] 2021-10-30 20:15
So the issue is that in the predicate `has_a(Wt,Pn,Pt,X)` you want to use `X` for many different things.

You just have to be creative about ways of distinguishing between different terms so you don't have to employ tricks like `C=X+1`.  In fact having to use these tricks is often an indicator that your fact format is not as intuitive or readable as it could be. 

For example, there is nothing in `(wheel, 4)` and `(door, (2,5))` to really indicate what those numbers mean.  Simply changing it to `(wheel, exact, 4)` and `(door, range, (2,5))` already adds some readability and gives you an easy way of distinguishing between the different uses. 

If you want `X` to take on even more uses then you could considered adding an extra term `has_a(Wt,Pn,Pt,Type,X)`, where `Type` could be `cardinality`, `color`, etc, to indicate what value `X` is going to be.

**Closed** 2021-11-02 09:45 UTC
Labels: question
