### ISSUE TITLE
extend_model function not usable with quiet option (wip only)

### ISSUE THREAD

**Issue by MaxOstrowski** [potassco/clingo#109] opened 2018-05-29 14:19 UTC
The extend_model function is called whenever a model is printed (not found) as documented.
Together with the quiet option for e.g. only printing the last model, this is not usable, as there is no reliable way to find out what was the last model.
(check on total assignments does not necessary mean that a model is found)

**Comment by rkaminsk** [comment] 2018-05-29 15:35
@BenKaufmann Just to comment why this is a problem:

To produce reasonable symbols to extend the model with, propagators need state information based on the assignment when the model was found. For example, the difference logic propagator maintains assignments of integers to variables. These change during propagation.

Currently, the propagator does not know when a model was found (and total fixpoints are not quite the same). One can of course store the last assignment in the model callback of the solve function but this is quite a tour through the interface.

I can imagine multiple ways to fix this.
1. The solver could call `expand_model` right away and the expanded symbols would be stored in clasp's intermediate solution, which is printed later.
2. A propagator could not just have an `expand_model` callback but also have a `store_model`/`on_model` callback, which would give the propagator the possibility to store the necessary information to expand the model later.
3. We could pass clasp's intermediate solution to the `expand_model` callback. The propagator would then have to expand the solution based on the intermediate solution.

Some notes:
1. The first way is certainly the easiest one to use but can be quite inefficient if a lot of symbols are created.
2. The second one allows for maintaining an efficient data structure to be able to expand a solution later. Unfortunately, this is quite low-level making it easier to implement things wrongly.
3. The last one would store no additional information but it might be quite cumbersome to expand the solution. In the difference logic propagator case, the integer assignments would have to be recalculated based on the intermediate model. Also with cautious and brave enumeration things get weird. If I remember correctly, clasp's intermediate solution is not quite an assignment.

To me it looks like we have to make a decision between 1 and 2. But maybe someone has a better idea.

**Comment by BenKaufmann** [comment] 2018-05-30 18:32
Hi,

I feel that I'm out of the loop here. There is no such thing as an "expand model" function in clasp. There is some `OutputTable::Theory`, which as its description indicates is a "callback for getting additional theory output" to be printed when a model is found. Of course, clasp only calls this if output is actually requested. If you ask the solver "to be quite", it certainly won't ask you for "more output".  

So, this "bug" looks more like a feature-request to me. If this is indeed a request to extend the propagator interface, it would be cool if you could describe what you actually want to achieve in the end. Should clasp "get something" from the expansion or is this simply about getting notified once a model was found (i.e. once all propagators decided that some total assignment is indeed a valid model).

**Comment by rkaminsk** [comment] 2018-05-30 19:11
I consider this a bug because the current interface is hard to use correctly (with the quiet option). In my notes above I was trying to explain that extending the propagator would be *one way* to make it a little easier. To be honest, I do not remember exactly how this feature was implemented. I guess we (Max) can also implement something without touching the clasp source. Like storing the symbols the moment a solution is found. And clasp's output can get the string representation from this later only if the solution is printed.

**Comment by BenKaufmann** [comment] 2018-05-30 19:55
Hi,

I would be happy to help but I'm not yet at the point where I can think about "how to fix" stuff because I'm not sure what problem we are trying to solve. I only remember why we added the Theory callback but it seems that meanwhile the requirements have changed.

**Comment by rkaminsk** [comment] 2018-05-30 20:11
I don't know what you where discussing. Below I put a problematic trace when generating theory-specific output. If that doesn't help, we have to wait for Max to enter the discussion tomorrow:
- solving starts
- propagator sets internal state (a)
- there is a model, which is stored for later output because of the quiet option
- solving continues
- propagator sets internal state (b)
- the problem is unsatisfiable
- the last model is printed
  - generating the theory-specific output requires the state from (a)
  - Max and Philip where having problems because they where generating the output based on state (b)

**Comment by BenKaufmann** [comment] 2018-06-03 18:42
Hi,

I agree that the behaviour of clasp for `--quiet=1` is wrong. If this is really the only problem you have with the current interface, I guess the easiest fix would be to always call the `OutputTable::Theory` callback and save its result so that it can be printed later. Of course, this won't change the behaviour of `--quiet=2` and it would also not work if clasp's output is disabled (`outf=3`).

**Comment by rkaminsk** [comment] 2018-06-03 19:41
Thanks for looking into it. Please don't fix anything yet. There is also the clingo API side, which does not care about the strings passed to clasp's output but the symbols added in the propagator. This has to work with `outf=3`, too. I'll look into it and also provide points in the code where what happens. Then I can tell you what we need.

**Comment by MaxOstrowski** [comment] 2018-06-04 13:32
Sorry for delay, I was busy with some projects.
I looked into it, and for the normal printing within clasp we derive from Clasp::OutputTable::Theory.
This one has two virtual functions, first/next which iterate through additional output (thereby calling the callback function given by the API).
Currently, the first/next functions return strings and are called in Output::printWitness.

Without two much insight I would suggest two things:
1. change the return values of Clasp::OutputTable::Theory to symbols (problably a SymbolVec or Span)
2. Call these function(s) in the Output::saveModel function (which is again called in Output::onModel)
and simply save the SymbolVector in the Output object.
With this I assume that we would get called on every model. @BenKaufmann Can you confirm or do you have any thoughts on this ?


The second thing is inspecting the Model in the onModel API callback.
There we currently use the ClingoModel::atoms function to call ClingoControl::addToModel which triggers the callback. This onModel API callback should be independent of the options --quiet and --outf and therefore be called on every model. The only drawback is that we have two different codepath for reaching the API extend_model callback.

I hope this was not too confusing and I could help.

**Comment by rkaminsk** [comment] 2018-06-05 15:40
@MaxOstrowski we can't put symbols in clasp's output table because clasp does not know anything about symbols.

I was looking at the current interface (from the clingo side) and actually don't like it very much. We should not force the user to use symbols in `Propagator.expand_model`. Rather it would be enough to have a general `on_model` function in a propagator, that unlike check, is called only when a model has been found. The user can then store intermediate information to generate output symbols there (or immediately symbols if she likes).

So I would suggest to remove `expand_model` from the propagator and have a generic `on_model` instead. To expand a model, we can equip the existing Model object with a function to add symbols to it. @BenKaufmann from the clasp side it would be important that a model is first yielded and printed when search is continued (or aborted). Is this possible? If this is not possible, we can also use a callback based solution, which we can add to the Control object.

I have the feeling that my suggestion above would fit a little better into the interfaces we have. A propagator in its current form should not have anything to do with output. It puts a little more programming effort on the user but nothing but the Propagator is kind of low-levelish  anyway.

**Comment by MaxOstrowski** [comment] 2018-06-06 07:41
@Roland My suggestion was not putting symbols into the output table but just storing symbols instead of strings in the class TheoryOutput that we derived from Clasp::OutputTable::Theory. So it would only be a slight change in the internal clasp interface.
Your interface (from the clingo side) seems a bit more complicated. It has the advantage that the propagator can store any kind of information during the propagator.on_model call, so no string conversion has to be done.
Currently I do not see a possibility to extend clasps native output with theory information in your interface.
Clasp does not access the clingo.Model for its output, so extending this won't help ?
PS: Thumbs up for using gender-mixed speech. ;-)

**Comment by BenKaufmann** [comment] 2018-06-09 14:56
@rkaminsk 

What do you mean by:

> from the clasp side it would be important that a model is first yielded and printed when search is continued (or aborted). 

In clasp, a search can have many solvers, each of which can have many post propagators. However, there is always only a single _enumerator_ to which models are committed *before* they are printed or further passed on to some external handler (e.g. clingo's on model callback). 
The flow is basically like this:

1. Solver i finds a total assignment
2. Solver i integrates all outstanding enumeration-related constraints and asks any post propagator whether the assignment is indeed a model
3.  Solver i commits the model to the enumerator, which does some final checking
4. If the model is relevant, it is passed to all external handlers (clasp output, model callbacks etc).
5. External handlers may commit new constraints to the enumerator. However, such constraints only apply to the following search and *not* to the model under consideration.
6. If any of the external handler returns false or enough models were enumerated, search stops.
7. Otherwise, all solvers eventually integrate any new constraints added in steps 3-5.

Hence, I guess clingo could actually call some propagator-specific `on_model` function in step 4 without any help of clasp.  However, such a function could not "invalidate" the current model. Furthermore, there is currently no interface for extending the model with theory-specific output information at this point. Of course, we could simply move the quite ugly `OutputTable::Theory` stuff to the model so that it becomes a (not particularly less ugly) Model::Theory.

**Comment by rkaminsk** [comment] 2018-06-10 15:41
I only had step 4 in mind. Having an `on_model` in a propagator was just an idea. Maybe we shouldn't even add it. Not adding output functionality to propagators, which after all just represent a bunch of constraints, might be a good idea.

What I would like to have is a function in the existing model class to add symbols, which should then appear in the output. When I talk about the model class, I mean the one in clingo not necessarily the one in clasp. We should just make sure that the user can access the thread-secific state of the propagator that found the model, which means that the propagator should not modify that thread-specific state while the model object is active. As far as I know, this is already the case.

When using python's `on_model` callbacks (called from the event handler) it is very easy to call them before the model is printed by the text output and, hence, injecting symbols for the output should be easy here. With `ClaspFacade::SolveHandle::model()` this cannot be done. As far as I can see, a model has already been printed before it is returned by this function.

**Comment by rkaminsk** [comment] 2018-06-22 16:59
Symbols can now be added in on_model callbacks.

**Closed by rkaminsk** 2018-06-22 16:59 UTC
Labels: bug
