### ISSUE TITLE
Build fails on Archlinux ARM

### ISSUE THREAD

**Issue by vbmithr** [potassco/clingo#12] opened 2016-11-02 19:32 UTC
Build log here: http://pastebin.com/7uX5Kgda

**Comment by rkaminsk** [comment] 2016-11-05 11:06
On my OS Python's hashfunc is defined as
  typedef long (*hashfunc)(PyObject *);
Apparently, for the ARM version the return value is int. I will look into how to fix this. For now, you could simply build without python support. -R

**Comment by rkaminsk** [comment] 2016-11-07 13:23
The issue is fixed in the cmake branch I am currently working on. The upcoming 5.2 release will contain the fix.

**Closed** 2017-04-24 21:28 UTC
Labels: bug
