### ISSUE TITLE
Grounding of silent variables leads to missing answer sets

### ISSUE THREAD

**Issue by Aluriak** [potassco/clingo#46] opened 2017-06-28 16:07 UTC
I tested the following code using clingo 5. Comments explain expected and found answer sets
(note that all answer sets contain `obj/1` and `att/1` atoms).

    % run: clingo -n 0 concept.lp
    % Context described by:
    %   e f h
    % b   x
    % c x x x
    % d x x

    rel(b,f).
    rel(c,(e;f;h)).
    rel(d,(e;f)).

    % Generating the concepts.
    obj(X):- rel(X,_) ; rel(X,Y): att(Y).
    att(Y):- rel(_,Y) ; rel(X,Y): obj(X).

    % The following constraint is not correctly grounded.
    :- not obj(_).
    %:- not obj(X):obj(X).  % this one is correctly grounded

    #show obj/1.
    #show att/1.

For reference, this is the expected answer sets (found with `clingo -n 0 concept.lp`) and clingo 5:

    clingo version 5.2.0
    Reading from simple.lp
    Solving...
    Answer: 1
    att(f) obj(c) att(h) att(e)
    Answer: 2
    att(f) obj(c) obj(d) obj(b)
    Answer: 3
    att(f) obj(c) att(e) obj(d)
    SATISFIABLE

And here is the result of the non-correctly grounded program:

    clingo version 5.2.0
    Solving...
    Answer: 1
    att(f) obj(d) obj(c) att(e)
    Answer: 2
    att(f) obj(d) obj(c) obj(b)
    SATISFIABLE

In other word: with the first constraint enable, 1 answer sets are unexpectedly discarded.
This holds for clingo 5.
In case of clingo 4.5.3 and 4.5.4, 2 answer sets are discarded.

This unexpected behaviors can be fixed (whatever the clasp version)
by avoiding the use of silent variables in constraint:

    :- not obj(X):obj(X).

**Comment by rkaminsk** [comment] 2017-06-28 17:00
This looks like a regression in gringo 4.5. With clingo 4.4 the program is grounded as expected. It looks like newer clingo versions omit some rules. I am going to investigate this further but this might take some time.

**Comment by rkaminsk** [comment] 2017-06-28 17:09
The problem is that the component

    obj(X):- rel(X,_) ; rel(X,Y): att(Y).
    att(Y):- rel(_,Y) ; rel(X,Y): obj(X).

is wrongly classified as a positive program, which in turn leads to wrong simplifications. If you add a dummy choice, you can workaround the problem:

    1 { c } 1.
    obj(X):- rel(X,_) ; rel(X,Y): att(Y); c.

**Comment by rkaminsk** [comment] 2017-06-28 17:31
Actually there might be an easy fix for this. I still have to think about this and produce some tests. If you like, you can try commit e6bb34f.

**Comment by Aluriak** [comment] 2017-06-30 15:37
I confirm that the patch fix the issue.

**Closed** 2017-08-01 19:45 UTC
Labels: bug
