### ISSUE TITLE
RuntimeError: redefinition of atom <'_',3006>

### ISSUE THREAD

**Issue by BenjaminCallewaertKUL** [potassco/clingo#301] opened 2021-04-27 11:34 UTC
The following ASP-code is a simplified version of an application that I'm writing for an HR company that wants to calculate it's wages with the use of ASP. The goal of the pyhton script is to incrementaly find the next timepoint where some action occurs. There are 2 types of actions: 1) walltime actions that are invoked at a prefixed timepoints 2) triggered actions that are invoked if a fluent has a certain value for some time ("after"-condition)

Once a timepoint is found by the script, it is added to the "nexpoints()" part of the ASP code and this part is subsequently re-solved to determine the influence of the addition of this timepoint and it's action on the values of the fluents.

But when running the program the following Runtime Error: "redefinition of atom <'__',3006>" is always thrown after the 4th solve-iteration. The program thus finds the first 3 timepoints, but then throws an error during the next solve. Since the atom that we're redefining is specified as '_' we're having a hard time finding the error. The problem really becomes odd if we add the "--text" command line option when running the program. In this case the program eventually finds the correct solution and does not throw an error.

Is there something wrong with repeatedly solving the same ASP-code or does the fault lie somewhere else?

Thanks in advance,

Benjamin Callewaert
PhD-candidate DTAI KU Leuven
```
#program timepoints().
timepoint(0).
day(0..1).
hour(0..23).
minute(0..59).
time(0,400).
ts(Days, Hours, Minutes, Stamp) :- day(Days), hour(Hours), minute(Minutes),Stamp = (Days*24+Hours)*60+Minutes.

action(A) :- walltimeAction(A).
action(A) :- triggeredAction(A).

fluent(timeOfDay).
domain(timeOfDay, (day; evening; night)).
initially(timeOfDay, day).
actionTime(morning, T) :- day(D), ts(D,6,0,T).
walltimeAction(morning).
causes(nightfall, timeOfDay, night).

domain(F, (true;false)) :- boolean(F).
initially(F,false) :- fluent(F), boolean(F).

fluent(onCall).	
boolean(onCall).	
walltimeAction(startOnCall).		
causes(startOnCall,onCall,true).	
actionTime(startOnCall,T):-day(D),ts(D,0,30,T).	

triggeredAction(makeBreakPossible).
after(onCall, true, OneHour, makeBreakPossible) :- ts(0,1,0,OneHour).

#program nextpoints().
initiated(F,Val,T) :- fluent(F),cause(F,Val,T),next(T1,T),timepoint(T),timepoint(T1),value(F,V2,T1), V2 != Val.
terminated(F,Val,T1) :- fluent(F),cause(F,V2,T),next(T1,T),timepoint(T),timepoint(T1),value(F,Val,T1), V2 != Val.

value(F,Val,0) :- fluent(F), initially(F,Val).
value(F,Val,T) :- fluent(F), timepoint(T), value(F,Val,T1), next(T1,T), not terminated(F,Val,T1).
value(F,Val,T) :- fluent(F), timepoint(T), initiated(F,Val,T).

cause(F,Val,T) :- action(A), happens(A,T), causes(A,F,Val,T), timepoint(T).
causes(A,F,Val,T) :- causes(A,F,Val),timepoint(T).

happens(A,T) :- walltimeAction(A), actionTime(A,T), timepoint(T).
happens(A,T2) :- after(F,V,D,A),timepoint(T),timepoint(T2),T2=T+D,sameSince(F,V,T,T2),initiated(F,Val,T).

sameSince(F,V,T1,T3) :- timepoint(T1),timepoint(T2), timepoint(T3), initiated(F,V,T1), not terminated(F,V,T2), not terminated(F,V,T3),T1<=T2,T2<T3.


#script (python)
import clingo

def main(prg):
	prg.ground([("timepoints", [])])
	for x in prg.symbolic_atoms.by_signature("time",2):
		start=x.symbol.arguments[0].number
		end=x.symbol.arguments[1].number
	currentpoint=start
	while currentpoint<end:
		prg.ground([("nextpoints", [])])
		prg.solve()
		for x in prg.symbolic_atoms.by_signature("timepoint",1):
			a=x.symbol.arguments[0].number
			if a>currentpoint:
				currentpoint=a
		nextpoint=Context.next(currentpoint,prg)
		if nextpoint==None or nextpoint>end:
			break
		timepointstr="timepoint("+str(nextpoint)+")."
		nextstr="next("+str(currentpoint)+","+str(nextpoint)+")."
		prg.add("nextpoints",[],nextstr)
		prg.add("nextpoints",[],timepointstr)
                currentpoint=nextpoint
	prg.solve()

class Context():	
	def next(currentpoint,prg):
		nextpoint=None
		for after in prg.symbolic_atoms.by_signature("after",4):
			activeSince=currentpoint
			fluent=after.symbol.arguments[0].name
			value=after.symbol.arguments[1].name
			duration=after.symbol.arguments[2].number
			for same in prg.symbolic_atoms.by_signature("sameSince", 4):
				xcurrentpoint=same.symbol.arguments[3].number
				xfluent=same.symbol.arguments[0].name
				xvalue=same.symbol.arguments[1].name
				xactiveSince=same.symbol.arguments[2].number
				if xcurrentpoint==currentpoint and xfluent==fluent and xvalue==value:
						if activeSince>xactiveSince:
							activeSince=xactiveSince
			for i in prg.symbolic_atoms.by_signature("initiated", 3):
				if i.symbol.arguments[0].name==fluent and i.symbol.arguments[1].name==value and i.symbol.arguments[2].number==activeSince:
					possiblePoint=duration+activeSince
					if nextpoint==None and possiblePoint>currentpoint:
						nextpoint=possiblePoint
					if possiblePoint>currentpoint and possiblePoint<nextpoint:
						nextpoint=possiblePoint	
		for x in prg.symbolic_atoms.by_signature("actionTime",2):
			a=x.symbol.arguments[1].number
			if nextpoint==None and a>currentpoint:
				nextpoint=a
			if a>currentpoint and a<nextpoint:
				nextpoint=a
		print("timepoint: "+str(nextpoint)+" is the next point")
		return nextpoint

	
#end.
#show happens/2.

```

**Comment by daveraja** [comment] 2021-04-27 12:01
I haven't looked carefully at your code but there are a at least a few basic things that don't look right. 

- Your "nextpoints" program should be parameterised (presumably with a time parameter). This is probably what is causing the error because you are re-grounding the same literals rather than extending your ASP program with new literals.  
- Your "timepoint/1" predicate should be declared as "#external"

Have a look at Section 6.3.2 Problem Encoding in the Potassco User Guide (https://github.com/potassco/guide/releases/download/v2.2.0/guide.pdf) for an example of incremental solving.

**Comment by rkaminsk** [comment] 2021-04-27 12:18
Dave is right. Programs have to be modular. If you ground a rule, solve, and then ground another rule with the same head, then your program is not modular. Grounding the same program with the same parameters twice is a bug (with the exception of programs consisting of integrity constraints only). Clingo does not detect this error in all cases and seemingly does the right thing sometimes. You should not rely on this. Your nextpoints program needs a parameter to prevent this from happening. Apart from the guide, there are also quite a few incremental/multi-shot programs among the clingo examples which might help to get an idea: unblock, solitaire, robots, consequences, ....

**Comment by BenjaminCallewaertKUL** [comment] 2021-04-27 14:48
Thank you for the quick response!!
I added a parameter that represents the found timepoint to the nextpoints(cp) part of the code and this seems to fix the problem. Should i still declare the timepoint/1 predicate if i include it in the nexpoints code?

`#program timepoints().
timepoint(0).
day(0..1).
hour(0..23).
minute(0..59).
time(0,2440).
ts(Days, Hours, Minutes, Stamp) :- day(Days), hour(Hours), minute(Minutes),Stamp = (Days*24+Hours)*60+Minutes.

action(A) :- walltimeAction(A).
action(A) :- triggeredAction(A).

actionTime(morning, T) :- day(D), ts(D,6,0,T).
walltimeAction(morning).

domain(F, (true;false)) :- boolean(F).
initially(F,false) :- fluent(F), boolean(F).

fluent(onCall).	
boolean(onCall).	
walltimeAction(startOnCall).		
causes(startOnCall,onCall,true).	
actionTime(startOnCall,T):-day(D),ts(D,0,30,T).	

triggeredAction(makeBreakPossible).
after(onCall, true, OneHour, makeBreakPossible) :- ts(0,1,0,OneHour).

value(F,Val,0) :- fluent(F), initially(F,Val).

#program nextpoints(cp).
timepoint(cp).

initiated(F,Val,cp) :- fluent(F),cause(F,Val,cp),next(T1,cp),timepoint(cp),timepoint(T1),value(F,V2,T1), V2 != Val.
terminated(F,V2,T1) :- fluent(F),cause(F,Val,cp),next(T1,cp),timepoint(cp),timepoint(T1),value(F,V2,T1), V2 != Val.

value(F,Val,cp) :- fluent(F), timepoint(cp), value(F,Val,T1), next(T1,cp), not terminated(F,Val,T1).
value(F,Val,cp) :- fluent(F), timepoint(cp), initiated(F,Val,cp).

cause(F,Val,cp) :- action(A), happens(A,cp), causes(A,F,Val,cp), timepoint(cp).
causes(A,F,Val,cp) :- causes(A,F,Val),timepoint(cp).

happens(A,cp) :- walltimeAction(A), actionTime(A,cp), timepoint(cp).
happens(A,cp) :- after(F,V,D,A),timepoint(T2),timepoint(cp),cp=T2+D,sameSince(F,V,T2,cp),initiated(F,V,T2).

sameSince(F,V,T1,cp) :- timepoint(T1),timepoint(T2), timepoint(cp), initiated(F,V,T1), not terminated(F,V,T2), not terminated(F,V,cp),T1<=T2,T2<cp.

#script (python)
import clingo

def main(prg):
	prg.ground([("timepoints", [])])
	for x in prg.symbolic_atoms.by_signature("time",2):
		start=x.symbol.arguments[0].number
		end=x.symbol.arguments[1].number
	currentpoint=start
	previouspoint=start
	while currentpoint<end:
		nextpoint=Context.next(currentpoint,prg)
		if nextpoint==None or nextpoint>end:
			break
		previouspoint=currentpoint
		currentpoint=nextpoint
		nextstr="next("+str(previouspoint)+","+str(currentpoint)+")."
		prg.add("nextpoints",[int(currentpoint)],nextstr)
		prg.ground([("nextpoints", [int(currentpoint)])])
		prg.solve()
	prg.solve()

class Context():	
	def next(currentpoint,prg):
		nextpoint=None
		for after in prg.symbolic_atoms.by_signature("after",4):
			activeSince=currentpoint
			fluent=after.symbol.arguments[0].name
			value=after.symbol.arguments[1].name
			duration=after.symbol.arguments[2].number
			for same in prg.symbolic_atoms.by_signature("sameSince", 4):
				xcurrentpoint=same.symbol.arguments[3].number
				xfluent=same.symbol.arguments[0].name
				xvalue=same.symbol.arguments[1].name
				xactiveSince=same.symbol.arguments[2].number
				if xcurrentpoint==currentpoint and xfluent==fluent and xvalue==value:
						if activeSince>xactiveSince:
							activeSince=xactiveSince
			for i in prg.symbolic_atoms.by_signature("initiated", 3):
				ifluent=i.symbol.arguments[0].name
				ivalue=i.symbol.arguments[1].name
				iActiveSince=i.symbol.arguments[2].number
				if ifluent==fluent and ivalue==value and iActiveSince==activeSince:
					possiblePoint=duration+activeSince
					if nextpoint==None and possiblePoint>currentpoint:
						nextpoint=possiblePoint
					if possiblePoint>currentpoint and possiblePoint<nextpoint:
						nextpoint=possiblePoint	
		for x in prg.symbolic_atoms.by_signature("actionTime",2):
			a=x.symbol.arguments[1].number
			if nextpoint==None and a>currentpoint:
				nextpoint=a
			if a>currentpoint and a<nextpoint:
				nextpoint=a
		print("timepoint: "+str(nextpoint)+" is the next point")
		return nextpoint

	
#end.

#show value/3.
#show happens/2.
`

**Comment by daveraja** [comment] 2021-04-27 23:01
No, "timepoint/1" shouldn't be declared as "#external" as it defined as part of each "nextpoints(cp)" module. 

One thing to watch for is that you are doing some tricky things with programmatically extending the (unground) logic program with a "next/2" instance every time you ground a new "nextpoints(cp)" module. I have to admit that I didn't realise that extending the unground logic program as part of an incremental grounding-solving loop would actually work, but since it does, it makes it tricky to understand what the semantics of your program is meant to be.

More concretely, "next(T,cp)" is being dynamically generated and grounded for each "nextpoints(cp)". You then use it in the lines:

    terminated(F,V2,T1) :- fluent(F),cause(F,Val,cp),next(T1,cp),timepoint(cp),timepoint(T1),value(F,V2,T1), V2 != Val.
    value(F,Val,cp) :- fluent(F), timepoint(cp), value(F,Val,T1), next(T1,cp), not terminated(F,Val,T1).
    sameSince(F,V,T1,cp) :- timepoint(T1),timepoint(T2), timepoint(cp), initiated(F,V,T1), not terminated(F,V,T2), not terminated(F,V,cp),T1<=T2,T2<cp.

So whether some instance of "terminated/3" holds for a time point T is determined by a definition of "next(T,cp)" that is added to your program later. But that could then be used to do determine whether "value/3" and "sameSince/3" hold for the current time point. 

To me this looks potentially problematic, as the value of a specific instance of "terminated/3" may initially be false (or simply that it hasn't been defined) and later becomes true. So the semantics of your program changes based on when you define the instances of "next/2" during the extend-ground-solve cycle. 

This may in fact be what you want, but could also lead to some unexpected behaviour.

**Comment by rkaminsk** [comment] 2021-04-28 14:12
Dave is right again. :smile: The `terminated` predicate should also be tagged with the current timestep. I would also recommend to write the encoding in a way that rules only refer to the previous and the current timepoint, possible introducing additional atoms. If you have rules referring to the current and all previous timepoints then you have quadratic growth baked into your encoding and you encoding will only scale up to a small horizon.

**Comment by JoD** [comment] 2021-05-12 17:21
@daveraja @rkaminsk Thanks for the feedback! @BenjaminCallewaertKUL implemented your ideas, and today he sent a mail reporting that his program now works quite well, way faster than the non-incremental version. 

So yeah, if it's still needed, I think the issue can be closed. Thanks again for your help!

**Comment by rkaminsk** [comment] 2021-05-12 18:34
Great! Then I am also closing this issue.

**Closed by rkaminsk** 2021-05-12 18:34 UTC
Labels: question
