### ISSUE TITLE
Exiting clingo while grounding using signals

### ISSUE THREAD

**Issue by javier-romero** [potassco/clingo#83] opened 2018-01-17 14:01 UTC
Hi,

It would be nice if the ground(...) function could be interrupted in a similar way as the solve(...) one.
For example, when interrupting the following program with C-c it does not stop:

```python
import clingo
import signal
import sys

def signal_handler(signum, frame):
    print("signal caught")
    sys.exit(1)

signal.signal(signal.SIGINT, signal_handler)
ctl = clingo.Control()
ctl.add("base",[],"""
#const n=500.
b(1..n,1..n,1..n).
""")
ctl.ground([("base",[])])
```

Thank you!
Javier

**Comment by rkaminsk** [comment] 2018-01-17 14:11
duplicate of #82

**Closed by rkaminsk** 2018-01-17 14:11 UTC
Labels: duplicate
